"use client";

import { PERMISSIONS } from "@/lib/permissions";

export const permissionGroups = [
  {
    title: "التجاوز الكامل",
    permissions: [PERMISSIONS.ADMIN_BYPASS],
  },
  {
    title: "المستخدمون",
    permissions: [PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_MANAGE, PERMISSIONS.STUDENTS_VIEW],
  },
  {
    title: "المحتوى والتعلم",
    permissions: [
      PERMISSIONS.SUBJECTS_VIEW,
      PERMISSIONS.SUBJECTS_MANAGE,
      PERMISSIONS.OWN_SUBJECTS_MANAGE,
      PERMISSIONS.LEARNING_PATHS_VIEW,
      PERMISSIONS.LEARNING_PATHS_MANAGE,
      PERMISSIONS.BOOKS_VIEW,
      PERMISSIONS.BOOKS_MANAGE,
      PERMISSIONS.OWN_BOOKS_MANAGE,
      PERMISSIONS.RESOURCES_VIEW,
      PERMISSIONS.RESOURCES_MANAGE,
      PERMISSIONS.OWN_RESOURCES_MANAGE,
      PERMISSIONS.EXAMS_VIEW,
      PERMISSIONS.EXAMS_MANAGE,
      PERMISSIONS.OWN_EXAMS_MANAGE,
    ],
  },
  {
    title: "المجتمع والعمليات",
    permissions: [
      PERMISSIONS.FORUM_VIEW,
      PERMISSIONS.FORUM_MODERATE,
      PERMISSIONS.FORUM_MANAGE,
      PERMISSIONS.BLOG_VIEW,
      PERMISSIONS.BLOG_MANAGE,
      PERMISSIONS.COMMENTS_VIEW,
      PERMISSIONS.COMMENTS_MODERATE,
      PERMISSIONS.EVENTS_VIEW,
      PERMISSIONS.EVENTS_MANAGE,
      PERMISSIONS.ANNOUNCEMENTS_VIEW,
      PERMISSIONS.ANNOUNCEMENTS_MANAGE,
      PERMISSIONS.AUDIT_LOGS_VIEW,
      PERMISSIONS.LIVE_MONITOR_VIEW,
    ],
  },
  {
    title: "التحليلات والإدارة",
    permissions: [
      PERMISSIONS.DASHBOARD_VIEW,
      PERMISSIONS.ANALYTICS_VIEW,
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.SETTINGS_VIEW,
      PERMISSIONS.AI_MANAGE,
      PERMISSIONS.MARKETING_VIEW,
      PERMISSIONS.AB_TESTING_VIEW,
    ],
  },
  {
    title: "التحفيز",
    permissions: [
      PERMISSIONS.CHALLENGES_VIEW,
      PERMISSIONS.CHALLENGES_MANAGE,
      PERMISSIONS.OWN_CHALLENGES_MANAGE,
      PERMISSIONS.CONTESTS_VIEW,
      PERMISSIONS.CONTESTS_MANAGE,
      PERMISSIONS.ACHIEVEMENTS_VIEW,
      PERMISSIONS.ACHIEVEMENTS_MANAGE,
      PERMISSIONS.REWARDS_VIEW,
      PERMISSIONS.REWARDS_MANAGE,
      PERMISSIONS.SEASONS_VIEW,
      PERMISSIONS.SEASONS_MANAGE,
      PERMISSIONS.TEACHERS_VIEW,
      PERMISSIONS.TEACHERS_MANAGE,
    ],
  },
] as const;