"use client";

import { PERMISSIONS } from "@/lib/permissions";

export const permissionLabels: Record<string, string> = {
  [PERMISSIONS.ADMIN_BYPASS]: "تجاوز كامل للصلاحيات (وصول غير مقيد)",
  [PERMISSIONS.DASHBOARD_VIEW]: "عرض لوحة التحكم",
  [PERMISSIONS.ANALYTICS_VIEW]: "عرض التحليلات",
  [PERMISSIONS.REPORTS_VIEW]: "عرض التقارير",
  [PERMISSIONS.USERS_VIEW]: "عرض المستخدمين",
  [PERMISSIONS.USERS_MANAGE]: "إدارة المستخدمين",
  [PERMISSIONS.STUDENTS_VIEW]: "عرض الطلاب",
  [PERMISSIONS.SUBJECTS_VIEW]: "عرض المواد",
  [PERMISSIONS.SUBJECTS_MANAGE]: "إدارة المواد",
  [PERMISSIONS.OWN_SUBJECTS_MANAGE]: "إدارة المواد الخاصة",
  [PERMISSIONS.LEARNING_PATHS_VIEW]: "عرض مسارات التعلم",
  [PERMISSIONS.LEARNING_PATHS_MANAGE]: "إدارة مسارات التعلم",
  [PERMISSIONS.BOOKS_VIEW]: "عرض الكتب",
  [PERMISSIONS.BOOKS_MANAGE]: "إدارة الكتب",
  [PERMISSIONS.OWN_BOOKS_MANAGE]: "إدارة الكتب الخاصة",
  [PERMISSIONS.RESOURCES_VIEW]: "عرض الموارد",
  [PERMISSIONS.RESOURCES_MANAGE]: "إدارة الموارد",
  [PERMISSIONS.OWN_RESOURCES_MANAGE]: "إدارة الموارد الخاصة",
  [PERMISSIONS.EXAMS_VIEW]: "عرض الاختبارات",
  [PERMISSIONS.EXAMS_MANAGE]: "إدارة الاختبارات",
  [PERMISSIONS.OWN_EXAMS_MANAGE]: "إدارة الاختبارات الخاصة",
  [PERMISSIONS.TEACHERS_VIEW]: "عرض المعلمين",
  [PERMISSIONS.TEACHERS_MANAGE]: "إدارة المعلمين",
  [PERMISSIONS.SEASONS_VIEW]: "عرض المواسم",
  [PERMISSIONS.SEASONS_MANAGE]: "إدارة المواسم",
  [PERMISSIONS.CHALLENGES_VIEW]: "عرض التحديات",
  [PERMISSIONS.CHALLENGES_MANAGE]: "إدارة التحديات",
  [PERMISSIONS.OWN_CHALLENGES_MANAGE]: "إدارة التحديات الخاصة",
  [PERMISSIONS.CONTESTS_VIEW]: "عرض المسابقات",
  [PERMISSIONS.CONTESTS_MANAGE]: "إدارة المسابقات",
  [PERMISSIONS.BLOG_VIEW]: "عرض المدونة",
  [PERMISSIONS.BLOG_MANAGE]: "إدارة المدونة",
  [PERMISSIONS.FORUM_VIEW]: "عرض المنتدى",
  [PERMISSIONS.FORUM_MODERATE]: "إشراف المنتدى",
  [PERMISSIONS.FORUM_MANAGE]: "إدارة المنتدى",
  [PERMISSIONS.COMMENTS_VIEW]: "عرض التعليقات",
  [PERMISSIONS.COMMENTS_MODERATE]: "إشراف التعليقات",
  [PERMISSIONS.EVENTS_VIEW]: "عرض الفعاليات",
  [PERMISSIONS.EVENTS_MANAGE]: "إدارة الفعاليات",
  [PERMISSIONS.ANNOUNCEMENTS_VIEW]: "عرض الإعلانات",
  [PERMISSIONS.ANNOUNCEMENTS_MANAGE]: "إدارة الإعلانات",
  [PERMISSIONS.ACHIEVEMENTS_VIEW]: "عرض الإنجازات",
  [PERMISSIONS.ACHIEVEMENTS_MANAGE]: "إدارة الإنجازات",
  [PERMISSIONS.REWARDS_VIEW]: "عرض المكافآت",
  [PERMISSIONS.REWARDS_MANAGE]: "إدارة المكافآت",
  [PERMISSIONS.AI_MANAGE]: "إدارة أدوات الذكاء",
  [PERMISSIONS.LIVE_MONITOR_VIEW]: "مراقبة العمليات الحية",
  [PERMISSIONS.MARKETING_VIEW]: "عرض التسويق",
  [PERMISSIONS.AB_TESTING_VIEW]: "عرض اختبارات A/B",
  [PERMISSIONS.SETTINGS_VIEW]: "عرض الإعدادات",
  [PERMISSIONS.AUDIT_LOGS_VIEW]: "عرض سجل التدقيق",
};