BEGIN;
SET lock_timeout = '10s';
CREATE INDEX IF NOT EXISTS "fkidx_User_referred_by_id" ON "User" (referred_by_id);
CREATE INDEX IF NOT EXISTS "fkidx_IpWhitelistEntry_created_by" ON "IpWhitelistEntry" (created_by);
CREATE INDEX IF NOT EXISTS "fkidx_BlockedIpAttempt_user_id" ON "BlockedIpAttempt" (user_id);
CREATE INDEX IF NOT EXISTS "fkidx_security_events_resolved_by" ON security_events (resolved_by);
CREATE INDEX IF NOT EXISTS "fkidx_blocked_tokens_user_id" ON blocked_tokens (user_id);
CREATE INDEX IF NOT EXISTS "fkidx_blacklisted_ips_blocked_by" ON blacklisted_ips (blocked_by);
CREATE INDEX IF NOT EXISTS "fkidx_CourseChangelog_user_id" ON "CourseChangelog" (user_id);
CREATE INDEX IF NOT EXISTS "fkidx_CourseReviewComment_reviewer_id" ON "CourseReviewComment" (reviewer_id);
CREATE INDEX IF NOT EXISTS "fkidx_course_versions_created_by" ON course_versions (created_by);
CREATE INDEX IF NOT EXISTS "fkidx_course_review_submissions_reviewer_id" ON course_review_submissions (reviewer_id);
CREATE INDEX IF NOT EXISTS "fkidx_course_assistants_invited_by" ON course_assistants (invited_by);
CREATE INDEX IF NOT EXISTS "fkidx_course_changelogs_changed_by" ON course_changelogs (changed_by);
CREATE INDEX IF NOT EXISTS "fkidx_lesson_drip_schedules_created_by" ON lesson_drip_schedules (created_by);
CREATE INDEX IF NOT EXISTS "fkidx_course_availability_windows_created_by" ON course_availability_windows (created_by);
CREATE INDEX IF NOT EXISTS "fkidx_Affiliate_approved_by" ON "Affiliate" (approved_by);
CREATE INDEX IF NOT EXISTS "fkidx_AffiliateCampaign_created_by" ON "AffiliateCampaign" (created_by);
CREATE INDEX IF NOT EXISTS "fkidx_AffiliatePayout_processed_by" ON "AffiliatePayout" (processed_by);
CREATE INDEX IF NOT EXISTS "fkidx_AffiliateSetting_updated_by" ON "AffiliateSetting" (updated_by);
CREATE INDEX IF NOT EXISTS "fkidx_AffiliateAudit_actor_id" ON "AffiliateAudit" (actor_id);
CREATE INDEX IF NOT EXISTS "fkidx_OrderItem_subject_id" ON "OrderItem" (subject_id);
CREATE INDEX IF NOT EXISTS "fkidx_UserAdminNote_created_by" ON "UserAdminNote" (created_by);
CREATE INDEX IF NOT EXISTS "fkidx_UserAdminNote_updated_by" ON "UserAdminNote" (updated_by);
CREATE INDEX IF NOT EXISTS "fkidx_AntiCheatFlag_reviewer_id" ON "AntiCheatFlag" (reviewer_id);
COMMIT;
